### ISSUE TITLE
Using name as the id for characters causes problems

### ISSUE THREAD

**Issue by mina-kleid** [Rostlab/JS16_ProjectA#92] opened 2016-03-19 07:34 UTC
As discussed before name is used as the id for characters, when i get the character by name i get multiple results( i.e. https://got-api.bruck.me/api/characters/Walder%20Frey )

**Comment by ghost** [comment] 2016-03-19 07:58
The api is actually not case-sensitive and does not need the whole name, because this has been requested by others in issue #50 . 

I am not sure how to solve both requirements now. 
But it is definitely a bit ugly to filter the one character that should be addressed on the other side of the api.

 Probably we will need a changed api, where there is one call for the unique record and one call with a flag, that gives me the hint that there is not the unique record requested, but all records that match the pattern case-insensitively. 
@sacdallago What is here probably the best solution?

**Comment by sacdallago** [comment] 2016-03-19 10:48
@Adiolis Why don't you implement another url encoded attribute `strict` that if set to true will only generate the strict result (thus it being equal to the request):
https://got-api.bruck.me/api/characters/Walder%20Frey?strict=true
http://expressjs.com/en/api.html#req.query

**Comment by ghost** [comment] 2016-03-19 11:17
@sacdallago 
That´s what i meant with flags.
Ty =)

**Comment by kordianbruck** [comment] 2016-03-22 20:45
Duplicate of #100 #102 - will be fixed by either using the MD5 or slug.

**Comment by ghost** [comment] 2016-03-23 20:44
@sacdallago @mina-zaki 
I have implemented the strict option.
Just put ?strict=true behind the api url.

@kordianbruck Please update the doc.

**Comment by sacdallago** [comment] 2016-03-23 21:34
@mbandle this is what I was referring to earlier on skype? The thing @gyachdav told you about. Don't know feasibility. Just throwing things around

Thanks @Adiolis

**Comment by ghost** [comment] 2016-03-24 19:41
@sacdallago Why is this here open? :smile: 
Makes me crazy with the Feature freeze milestone ;)

**Comment by sacdallago** [comment] 2016-03-25 07:47
I did reopen this? Must have pressed the button by mistake on my not-so-smart phone

**Closed as completed by sacdallago** 2016-03-25 07:47 UTC
Labels: duplicate
