### ISSUE TITLE
Get character gender

### ISSUE THREAD

**Issue by theocheslerean** [Rostlab/JS16_ProjectA#71] opened 2016-03-15 12:14 UTC

**Comment by theocheslerean** [comment] 2016-03-15 12:16
Idea 1: Count "his", "her" in the whole page
Idea 2: As observed, the second sentence in the wiki text, starts with either "he" or "she", with some exceptions

**Comment by ghost** [comment] 2016-03-15 12:31
Idea 2 might be problematic later on, when the wiki pages will change or new character pages don´t follow this pattern.

**Comment by togiberlin** [comment] 2016-03-15 12:51
@theocheslerean I agree, I guess Idea 1 sounds good.

**Comment by kordianbruck** [comment] 2016-03-15 18:08
@theocheslerean I need to rerun the filler I guess?

**Comment by sacdallago** [comment] 2016-03-15 22:23
Can you run a random test to see how accurate this actually is?

**Comment by sacdallago** [comment] 2016-03-15 22:23
P.s.: and report here

**Comment by kordianbruck** [comment] 2016-03-16 01:10
@sacdallago we now have the data in the db. Our amazing statistics show 1263 male vs 753 females - does that sound good? Check https://got-api.bruck.me/api/stats to see for yourself

**Comment by sacdallago** [comment] 2016-03-16 10:07
Is there anything to compare this data with? Get a _standard error_ for this?

**Comment by gyachdav** [comment] 2016-03-16 12:36
"cities":0
??

**Comment by kordianbruck** [comment] 2016-03-17 10:04
@sacdallago I've googled a bit, but there is nothing really clear out there on the web... But it sounds reasonable - GoT is a male dominated show with a few strong female characters.

Closing this for now, as it is resolved.

**Comment by gyachdav** [comment] 2016-03-17 10:34
what are "cities":0?

**Comment by kordianbruck** [comment] 2016-03-17 10:36
@gyachdav we are working on a city filler in #82

**Comment by sacdallago** [comment] 2016-03-17 15:35
@kordianbruck I don't remember with who I talked yesterday but @Adiolis was definitely there and knows how this can be random tested. Could you pls do this? just for the sake of it. Sample size 100 of most popular is fine.

**Comment by ghost** [comment] 2016-03-17 17:14
I can do the check ;)

**Comment by sacdallago** [comment] 2016-03-17 17:54
:D when machines can't solve every problem on the planet :dancer: Just know that if you get this > 90% right, you are gonna be the first online service to implement this information systematically :O

**Comment by ghost** [comment] 2016-03-17 18:04
Hm, i could fake this to > 90% =D
Well, i checked 100 characters.

Result:

20/100 Wrong.
19 wrong, because character is actually male.
1 wrong, because character is actually female.

Name - assumed male - is actually male - wrong?

> Viserys II Targaryen 1 1
> Walder Frey 1 1
> Willas Tyrell 1 1
> Wynafryd Manderly 0 0
> Yorkel 0 1 WRONG: IS MALE
> Zarabelo 0 1 WRONG: IS MALE
> Quentyn Qorgyle 0 1 WRONG: IS MALE
> Qyle 1 1
> Ragwyle 0 0
> Rat Cook 1 1
> 
> Redtusk 1 1
> Rhaegar Frey 1 1
> Rhogoro 1 1
> Richard Farrow 0 1 WRONG: IS MALE
> Rigney 1 1
> Robert Flowers 1 1
> Robin Potter 1 1
> Roggo 0 1 WRONG: IS MALE
> Ronel Rivers 0 1 WRONG: IS MALE
> Roone 1 1
> 
> Ryella Frey 0 0
> Salladhor Saan 1 1
> Sarra Frey 0 0
> Shyra 0 0
> Sloey 0 1 WRONG: IS MALE
> Stonehand 0 1 WRONG: IS MALE
> Tansy 0 0
> Three Toes 1 1
> Timoth 1 1
> Titus 1 1
> 
> Triston of Tally Hill 0 1 WRONG: IS MALE
> Tybolt Crakehall 1 1
> Tyrek Lannister 1 1
> Umar 0 1 WRONG: IS MALE
> Vaellyn 1 1
> Valaena Velaryon 0 0
> Vickon Greyjoy 1 1
> Vyman 0 1 WRONG: IS MALE
> Walda Rivers 0 0
> Aerion Targaryen 1 1
> 
> Aglantine 0 0
> Aggo 0 1 WRONG: IS MALE
> Alekyne Florent 1 1
> Alyce 1 0 WRONG: IS FEMALE
> Alyn 1 1
> Alys Arryn 0 0
> Andrew Estermont 1 1
> Anguy 1 1
> Arianne Martell 0 0
> Ashara Dayne 0 0
> Axell Florent 1 1
> 
> Bandy 0 0
> Barre 1 1
> Bellonara Otherys 0 0
> Ben Bones 1 1
> Benedict 0 1 WRONG: IS MALE
> Bess Bracken 0 0
> Bharbo 0 1 WRONG: IS MALE
> Brea 0 0
> Bronn 1 1
> Bump 1 1
> 
> Caleotte 1 1 
> Chiggen 1 1
> Clement 1 1
> Cley Cerwyn 1 1
> Coldhands 1 1
> Conwy 0 1 WRONG: IS MALE
> Corliss Penny 0 0
> Cynthea 0 0
> Daemon Targaryen 1 1
> Daeryssa 0 0
> 
> Dagmer 1 1
> Dalla (Dragonstone) 0 0
> Dancy 0 0
> Del 0 1 WRONG: IS MALE
> Deana Hardyng 0 0
> Denys Arryn 1 1
> Dick Follard 1 1
> Donnis 0 1 WRONG: IS MALE
> Dudley 1 1
> Easy 1 1
> 
> Eddison Tollett 1 1
> Eglantine 0 0
> Eldiss 1 1
> Ellaria Sand 0 0
> Elron 0 0
> Emma 0 0
> Erreck 1 1
> Ezzara 0 0
> Falia Flowers 0 0
> Fern 0 0
> 
> Fornio 1 1
> Fralegg 1 1
> Garigus 1 1
> Gavin 0 1 WRONG: IS MALE
> Gendry 1 1
> Gillam 1 1
> Goady 0 1 WRONG: IS MALE
> Grazdan 1 1
> Guyne 1 1
> Kirby Pimm 1 1

**Comment by sacdallago** [comment] 2016-03-17 19:07
Good, we are ±80% accurate, still better than anyone else on the planet

**Comment by gyachdav** [comment] 2016-03-17 20:53
Ways to improve:

use bag of words that fit a male profile to distinguish from female. Luckily for us the GoT world is chauvinist by design so the male profile should stands out by looking up:

title: king, prince, khal, lord, ser, magister,  maester, spymaster, knight, guard, guardsman, apprentice, spymaster etc.
marital: husband, father, grandfather, son, grandson, bastard. 
organization: kingsguard, queensguard, nightswatch, the small council ....
profession: hedge knight, innskeep, innkeeper, smuggler, captain, sellsword

you get the idea.

**Comment by gyachdav** [comment] 2016-03-25 19:37
was the above ever tried? has the accuracy improved?

**Comment by ghost** [comment] 2016-03-25 20:24
@theocheslerean 

Because this is an improvement and no new feature, i change the milestone.

**Comment by sacdallago** [comment] 2016-03-26 11:55
And since this seems to be something that doesn't affect functionality and @gyachdav can be tested in a week :laughing:

**Closed as completed** 2016-04-05 09:57 UTC
Labels: enhancement
